// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Controllers
{
    public partial class PostalAddressController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PostalAddressController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CreatePostalAddress()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreatePostalAddress);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ModifyPostalAddress()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ModifyPostalAddress);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ChangePrimary()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePrimary);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PostalAddressDetail()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PostalAddressDetail);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PostalAddressController Actions { get { return MVC.PostalAddress; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PostalAddress";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PostalAddress";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string CreatePostalAddress = "CreatePostalAddress";
            public readonly string ModifyPostalAddress = "ModifyPostalAddress";
            public readonly string ChangePrimary = "ChangePrimary";
            public readonly string PostalAddressDetail = "PostalAddressDetail";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string CreatePostalAddress = "CreatePostalAddress";
            public const string ModifyPostalAddress = "ModifyPostalAddress";
            public const string ChangePrimary = "ChangePrimary";
            public const string PostalAddressDetail = "PostalAddressDetail";
        }


        static readonly ActionParamsClass_CreatePostalAddress s_params_CreatePostalAddress = new ActionParamsClass_CreatePostalAddress();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CreatePostalAddress CreatePostalAddressParams { get { return s_params_CreatePostalAddress; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CreatePostalAddress
        {
            public readonly string parentId = "parentId";
            public readonly string type = "type";
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_ModifyPostalAddress s_params_ModifyPostalAddress = new ActionParamsClass_ModifyPostalAddress();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ModifyPostalAddress ModifyPostalAddressParams { get { return s_params_ModifyPostalAddress; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ModifyPostalAddress
        {
            public readonly string parentId = "parentId";
            public readonly string communicationId = "communicationId";
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_ChangePrimary s_params_ChangePrimary = new ActionParamsClass_ChangePrimary();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ChangePrimary ChangePrimaryParams { get { return s_params_ChangePrimary; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ChangePrimary
        {
            public readonly string id = "id";
            public readonly string parentId = "parentId";
            public readonly string status = "status";
        }
        static readonly ActionParamsClass_PostalAddressDetail s_params_PostalAddressDetail = new ActionParamsClass_PostalAddressDetail();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PostalAddressDetail PostalAddressDetailParams { get { return s_params_PostalAddressDetail; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PostalAddressDetail
        {
            public readonly string request = "request";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Detail = "_Detail";
                public readonly string _Repeater = "_Repeater";
                public readonly string CreatePostalAddress = "CreatePostalAddress";
                public readonly string ModifyPostalAddress = "ModifyPostalAddress";
            }
            public readonly string _Detail = "~/Views/PostalAddress/_Detail.cshtml";
            public readonly string _Repeater = "~/Views/PostalAddress/_Repeater.cshtml";
            public readonly string CreatePostalAddress = "~/Views/PostalAddress/CreatePostalAddress.cshtml";
            public readonly string ModifyPostalAddress = "~/Views/PostalAddress/ModifyPostalAddress.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PostalAddressController : ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Controllers.PostalAddressController
    {
        public T4MVC_PostalAddressController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void CreatePostalAddressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long parentId, ir.ankasoft.entities.Enums.PartyObjective type);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreatePostalAddress(long parentId, ir.ankasoft.entities.Enums.PartyObjective type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreatePostalAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            CreatePostalAddressOverride(callInfo, parentId, type);
            return callInfo;
        }

        [NonAction]
        partial void CreatePostalAddressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Models.PostalAddress.ViewModelCreateModifyPostalAddress request, ir.ankasoft.entities.Enums.PartyObjective type);

        [NonAction]
        public override System.Web.Mvc.ActionResult CreatePostalAddress(ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Models.PostalAddress.ViewModelCreateModifyPostalAddress request, ir.ankasoft.entities.Enums.PartyObjective type)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CreatePostalAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "type", type);
            CreatePostalAddressOverride(callInfo, request, type);
            return callInfo;
        }

        [NonAction]
        partial void ModifyPostalAddressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long parentId, long communicationId);

        [NonAction]
        public override System.Web.Mvc.ActionResult ModifyPostalAddress(long parentId, long communicationId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ModifyPostalAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "communicationId", communicationId);
            ModifyPostalAddressOverride(callInfo, parentId, communicationId);
            return callInfo;
        }

        [NonAction]
        partial void ModifyPostalAddressOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Models.PostalAddress.ViewModelCreateModifyPostalAddress request);

        [NonAction]
        public override System.Web.Mvc.ActionResult ModifyPostalAddress(ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Models.PostalAddress.ViewModelCreateModifyPostalAddress request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ModifyPostalAddress);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModifyPostalAddressOverride(callInfo, request);
            return callInfo;
        }

        [NonAction]
        partial void ChangePrimaryOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id, long parentId, bool status);

        [NonAction]
        public override System.Web.Mvc.ActionResult ChangePrimary(long id, long parentId, bool status)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ChangePrimary);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "parentId", parentId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "status", status);
            ChangePrimaryOverride(callInfo, id, parentId, status);
            return callInfo;
        }

        [NonAction]
        partial void PostalAddressDetailOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, System.Collections.Generic.List<ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Models.PostalAddress.ViewModelPostalAddress> request);

        [NonAction]
        public override System.Web.Mvc.ActionResult PostalAddressDetail(System.Collections.Generic.List<ir.ankasoft.bazyaftsazeh.ERP.FrontEndMVC.Models.PostalAddress.ViewModelPostalAddress> request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PostalAddressDetail);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            PostalAddressDetailOverride(callInfo, request);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
