// <auto-generated />
namespace ir.ankasoft.bazyaftsazeh.ERP.datalayer.EF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class contextmenuTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(contextmenuTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710150859258_contextmenuTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
