//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ir.ankasoft.resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ir.ankasoft.resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی تواند خالی باشد.
        /// </summary>
        public static string _0CanntBeEmpty {
            get {
                return ResourceManager.GetString("_0CanntBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی تواند برابر صفر باشد.
        /// </summary>
        public static string _0CanntBeEqualToZero {
            get {
                return ResourceManager.GetString("_0CanntBeEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نمی تواند کوچکتر یا مساوی {1} باشد.
        /// </summary>
        public static string _0CanntBeLowerEqualTo1 {
            get {
                return ResourceManager.GetString("_0CanntBeLowerEqualTo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید مابین {1} و {2} باشد.
        /// </summary>
        public static string _0MustBeBetween1And2 {
            get {
                return ResourceManager.GetString("_0MustBeBetween1And2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید انتخاب شود.
        /// </summary>
        public static string _0MustBeSelect {
            get {
                return ResourceManager.GetString("_0MustBeSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبان.
        /// </summary>
        public static string Aban {
            get {
                return ResourceManager.GetString("Aban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار پذیرفته شده.
        /// </summary>
        public static string AcceptedQty {
            get {
                return ResourceManager.GetString("AcceptedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ حسابداری.
        /// </summary>
        public static string AccountingDate {
            get {
                return ResourceManager.GetString("AccountingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مورد قبلا در سیستم ثبت شده است.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبل از ظهر.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجتمع انبارهای تقی زاده.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا برای ادامه انجام عملیات مطمئن هستید؟.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آذر.
        /// </summary>
        public static string Azar {
            get {
                return ResourceManager.GetString("Azar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بهمن.
        /// </summary>
        public static string Bahman {
            get {
                return ResourceManager.GetString("Bahman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف از خرید.
        /// </summary>
        public static string Cancellation {
            get {
                return ResourceManager.GetString("Cancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوقف شد.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ورود کلیک کنید.
        /// </summary>
        public static string ClickHereToLogIn {
            get {
                return ResourceManager.GetString("ClickHereToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طاقه.
        /// </summary>
        public static string Column {
            get {
                return ResourceManager.GetString("Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل شده.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید پست الکترونیکی.
        /// </summary>
        public static string ConfirmEmail {
            get {
                return ResourceManager.GetString("ConfirmEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طرف حساب.
        /// </summary>
        public static string CounterParty {
            get {
                return ResourceManager.GetString("CounterParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشورها.
        /// </summary>
        public static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کن.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد.
        /// </summary>
        public static string CreateNew {
            get {
                return ResourceManager.GetString("CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد دسته بندی جدید.
        /// </summary>
        public static string CreateNewCategory {
            get {
                return ResourceManager.GetString("CreateNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد رنگ جدید.
        /// </summary>
        public static string CreateNewColor {
            get {
                return ResourceManager.GetString("CreateNewColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد شرکت جدید.
        /// </summary>
        public static string CreateNewCompany {
            get {
                return ResourceManager.GetString("CreateNewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کشور جدید.
        /// </summary>
        public static string CreateNewCountries {
            get {
                return ResourceManager.GetString("CreateNewCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد واحد پولی.
        /// </summary>
        public static string CreateNewCurrency {
            get {
                return ResourceManager.GetString("CreateNewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد کد گروه جدید.
        /// </summary>
        public static string CreateNewGroupCode {
            get {
                return ResourceManager.GetString("CreateNewGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد واحد صنفی جدید.
        /// </summary>
        public static string CreateNewGuild {
            get {
                return ResourceManager.GetString("CreateNewGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد زبان جدید.
        /// </summary>
        public static string CreateNewLanguage {
            get {
                return ResourceManager.GetString("CreateNewLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد واحد اندازه گیری.
        /// </summary>
        public static string CreateNewMeasuringUnit {
            get {
                return ResourceManager.GetString("CreateNewMeasuringUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد منو جدید.
        /// </summary>
        public static string CreateNewMenuItem {
            get {
                return ResourceManager.GetString("CreateNewMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد بخش جدید.
        /// </summary>
        public static string CreateNewSection {
            get {
                return ResourceManager.GetString("CreateNewSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد فروشگاه جدید.
        /// </summary>
        public static string CreateNewStore {
            get {
                return ResourceManager.GetString("CreateNewStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد اطلاعات خودرویی جدید.
        /// </summary>
        public static string CreateVehicleInfo {
            get {
                return ResourceManager.GetString("CreateVehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد پول.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره قبض انبار گمرکی.
        /// </summary>
        public static string CustomsWarehouseReceiptNumber {
            get {
                return ResourceManager.GetString("CustomsWarehouseReceiptNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to داشبورد.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دقت اعشاری.
        /// </summary>
        public static string DecimalPrecision {
            get {
                return ResourceManager.GetString("DecimalPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف کردن.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شد.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه توضیحات.
        /// </summary>
        public static string DescriptionSummery {
            get {
                return ResourceManager.GetString("DescriptionSummery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازگیری مقصد.
        /// </summary>
        public static string DestinationUnitOfMeasure {
            get {
                return ResourceManager.GetString("DestinationUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مقصد.
        /// </summary>
        public static string DestinationValue {
            get {
                return ResourceManager.GetString("DestinationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دی.
        /// </summary>
        public static string Dey {
            get {
                return ResourceManager.GetString("Dey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل لینک.
        /// </summary>
        public static string EmailLink {
            get {
                return ResourceManager.GetString("EmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد وارد شده معتبر نمی باشد.
        /// </summary>
        public static string EnteredFieldNotValid {
            get {
                return ResourceManager.GetString("EnteredFieldNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پست الکترونیکی خود را وارد نمایید.
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مورد.
        /// </summary>
        public static string entries {
            get {
                return ResourceManager.GetString("entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در انجام عملیات.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسفند.
        /// </summary>
        public static string Esfand {
            get {
                return ResourceManager.GetString("Esfand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال به Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروردین.
        /// </summary>
        public static string Farvardin {
            get {
                return ResourceManager.GetString("Farvardin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاییدیه فراموشی رمز عبور.
        /// </summary>
        public static string ForgotPasswordConfirmation {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور خود را فراموش کرده اید.
        /// </summary>
        public static string ForgotYourPassword {
            get {
                return ResourceManager.GetString("ForgotYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کامل.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن ناخالص.
        /// </summary>
        public static string GrossWeight {
            get {
                return ResourceManager.GetString("GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد گروه.
        /// </summary>
        public static string GroupCode {
            get {
                return ResourceManager.GetString("GroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد صنفی.
        /// </summary>
        public static string Guild {
            get {
                return ResourceManager.GetString("Guild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد رنگ.
        /// </summary>
        public static string HexCode {
            get {
                return ResourceManager.GetString("HexCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال انجام.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالا.
        /// </summary>
        public static string Invent {
            get {
                return ResourceManager.GetString("Invent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره بچ.
        /// </summary>
        public static string InventBatchNumber {
            get {
                return ResourceManager.GetString("InventBatchNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار.
        /// </summary>
        public static string InventLocation {
            get {
                return ResourceManager.GetString("InventLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع مکان ذخیره سازی.
        /// </summary>
        public static string InventLocationType {
            get {
                return ResourceManager.GetString("InventLocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی انبار.
        /// </summary>
        public static string InventOnHand {
            get {
                return ResourceManager.GetString("InventOnHand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر حسب طرف حساب.
        /// </summary>
        public static string InventOnHandPerCounterParty {
            get {
                return ResourceManager.GetString("InventOnHandPerCounterParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر حسب طرف حساب و انبار.
        /// </summary>
        public static string InventOnHandPerCounterPartyAndInventLocation {
            get {
                return ResourceManager.GetString("InventOnHandPerCounterPartyAndInventLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سریال های کالا.
        /// </summary>
        public static string InventSerials {
            get {
                return ResourceManager.GetString("InventSerials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت انبار.
        /// </summary>
        public static string InventSite {
            get {
                return ResourceManager.GetString("InventSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تراکنش.
        /// </summary>
        public static string InventTransId {
            get {
                return ResourceManager.GetString("InventTransId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاکتور کردن.
        /// </summary>
        public static string Invoiced {
            get {
                return ResourceManager.GetString("Invoiced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ فاکتور.
        /// </summary>
        public static string InvoiceDate {
            get {
                return ResourceManager.GetString("InvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره فاکتور.
        /// </summary>
        public static string InvoiceNo {
            get {
                return ResourceManager.GetString("InvoiceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خودروی ایرانی.
        /// </summary>
        public static string IsIranianVehicle {
            get {
                return ResourceManager.GetString("IsIranianVehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO.
        /// </summary>
        public static string ISO {
            get {
                return ResourceManager.GetString("ISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISO3.
        /// </summary>
        public static string ISO3 {
            get {
                return ResourceManager.GetString("ISO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد کالا / SKU Code.
        /// </summary>
        public static string ItemId {
            get {
                return ResourceManager.GetString("ItemId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خرداد.
        /// </summary>
        public static string Khordad {
            get {
                return ResourceManager.GetString("Khordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین فعالیت ها.
        /// </summary>
        public static string LatestActivities {
            get {
                return ResourceManager.GetString("LatestActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول جغرافیایی.
        /// </summary>
        public static string LatitudeX {
            get {
                return ResourceManager.GetString("LatitudeX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عرض جغرافیایی.
        /// </summary>
        public static string LatitudeY {
            get {
                return ResourceManager.GetString("LatitudeY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس لینک/آدرس لینک خارجی.
        /// </summary>
        public static string LinkUrl {
            get {
                return ResourceManager.GetString("LinkUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ورود.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والد.
        /// </summary>
        public static string MasterParent {
            get {
                return ResourceManager.GetString("MasterParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازگیری کل.
        /// </summary>
        public static string MasterUnitOfMeasure {
            get {
                return ResourceManager.GetString("MasterUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر: 100 کاراکتر.
        /// </summary>
        public static string MaxLenght100 {
            get {
                return ResourceManager.GetString("MaxLenght100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد ارقام: 14 رقم.
        /// </summary>
        public static string MaxLenght14 {
            get {
                return ResourceManager.GetString("MaxLenght14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر: 20 کاراکتر.
        /// </summary>
        public static string MaxLenght20 {
            get {
                return ResourceManager.GetString("MaxLenght20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر: 5 کاراکتر.
        /// </summary>
        public static string MaxLenght5 {
            get {
                return ResourceManager.GetString("MaxLenght5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر تعداد کاراکتر: 6 کاراکتر.
        /// </summary>
        public static string MaxLenght6 {
            get {
                return ResourceManager.GetString("MaxLenght6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازه گیری.
        /// </summary>
        public static string MeasuringUnit {
            get {
                return ResourceManager.GetString("MeasuringUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مهر.
        /// </summary>
        public static string Mehr {
            get {
                return ResourceManager.GetString("Mehr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منو.
        /// </summary>
        public static string MenuItem {
            get {
                return ResourceManager.GetString("MenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل تعداد ارقام 11 رقم.
        /// </summary>
        public static string MinLenght11 {
            get {
                return ResourceManager.GetString("MinLenght11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موبایل.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش کن.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش رنگ.
        /// </summary>
        public static string ModifyColor {
            get {
                return ResourceManager.GetString("ModifyColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش شرکت.
        /// </summary>
        public static string ModifyCompany {
            get {
                return ResourceManager.GetString("ModifyCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش واحد پولی.
        /// </summary>
        public static string ModifyCurrency {
            get {
                return ResourceManager.GetString("ModifyCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش واحد صنفی.
        /// </summary>
        public static string ModifyGuild {
            get {
                return ResourceManager.GetString("ModifyGuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش واحد اندازگیری.
        /// </summary>
        public static string ModifyMeasuringUnit {
            get {
                return ResourceManager.GetString("ModifyMeasuringUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرداد.
        /// </summary>
        public static string Mordad {
            get {
                return ResourceManager.GetString("Mordad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیشتر.
        /// </summary>
        public static string More {
            get {
                return ResourceManager.GetString("More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن خالص.
        /// </summary>
        public static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدی.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد ارقام وارد شده باید بین 11 تا 14 رقم باشد.
        /// </summary>
        public static string NumberLenghMustBeBetween11And14Chars {
            get {
                return ResourceManager.GetString("NumberLenghMustBeBetween11And14Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string NumCode {
            get {
                return ResourceManager.GetString("NumCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از.
        /// </summary>
        public static string of {
            get {
                return ResourceManager.GetString("of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سفارش.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اردیبهشت.
        /// </summary>
        public static string Ordibehesht {
            get {
                return ResourceManager.GetString("Ordibehesht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبدا.
        /// </summary>
        public static string Origin {
            get {
                return ResourceManager.GetString("Origin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره شناسایی.
        /// </summary>
        public static string PartyNumber {
            get {
                return ResourceManager.GetString("PartyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string PersonalTitle {
            get {
                return ResourceManager.GetString("PersonalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلاک.
        /// </summary>
        public static string PlateNumber {
            get {
                return ResourceManager.GetString("PlateNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا پست الکترونیکی خود را برای رست کردن رمز عبور چک کنید.
        /// </summary>
        public static string PleaseCheckYourEmailToResetYourPassword {
            get {
                return ResourceManager.GetString("PleaseCheckYourEmailToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد از ظهر.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قبلی.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولید.
        /// </summary>
        public static string ProduceDate {
            get {
                return ResourceManager.GetString("ProduceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پیش فاکتور.
        /// </summary>
        public static string ProformaNo {
            get {
                return ResourceManager.GetString("ProformaNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل فرآیند.
        /// </summary>
        public static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش خرید/ دریافت.
        /// </summary>
        public static string PurchOrder {
            get {
                return ResourceManager.GetString("PurchOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت خرید.
        /// </summary>
        public static string PurchStatus {
            get {
                return ResourceManager.GetString("PurchStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع خرید.
        /// </summary>
        public static string PurchType {
            get {
                return ResourceManager.GetString("PurchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید.
        /// </summary>
        public static string Receipt {
            get {
                return ResourceManager.GetString("Receipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نمایش.
        /// </summary>
        public static string RecordsPerPage {
            get {
                return ResourceManager.GetString("RecordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی.
        /// </summary>
        public static string Recover {
            get {
                return ResourceManager.GetString("Recover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مرجع.
        /// </summary>
        public static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرا بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این مرورگر را بخاطر بسپار.
        /// </summary>
        public static string RememberThisBrowser {
            get {
                return ResourceManager.GetString("RememberThisBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشتن.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره درخواست.
        /// </summary>
        public static string RequestId {
            get {
                return ResourceManager.GetString("RequestId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار درخواستی.
        /// </summary>
        public static string RequetedQty {
            get {
                return ResourceManager.GetString("RequetedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فیلد ضروری می باشد.
        /// </summary>
        public static string RequiredFiled {
            get {
                return ResourceManager.GetString("RequiredFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقداردهی دوباره.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار دهی دوباره رمز عبور.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاییدیه مقداردهی دوباره رمز عبور.
        /// </summary>
        public static string ResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قفسه.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        public static string Saterday {
            get {
                return ResourceManager.GetString("Saterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته.
        /// </summary>
        public static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان دسته کلی.
        /// </summary>
        public static string SectionTitle {
            get {
                return ResourceManager.GetString("SectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب والد.
        /// </summary>
        public static string SelectParent {
            get {
                return ResourceManager.GetString("SelectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال کد تاییدیه.
        /// </summary>
        public static string SendVerificationCode {
            get {
                return ResourceManager.GetString("SendVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهریور.
        /// </summary>
        public static string Shahrivar {
            get {
                return ResourceManager.GetString("Shahrivar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامت.
        /// </summary>
        public static string Sign {
            get {
                return ResourceManager.GetString("Sign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازه گیری مبدا.
        /// </summary>
        public static string SourceUnitOfMeasure {
            get {
                return ResourceManager.GetString("SourceUnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار مبدا.
        /// </summary>
        public static string SourceValue {
            get {
                return ResourceManager.GetString("SourceValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اظهارنامه.
        /// </summary>
        public static string StatementNumber {
            get {
                return ResourceManager.GetString("StatementNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشگاه.
        /// </summary>
        public static string Store {
            get {
                return ResourceManager.GetString("Store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت به پایان رسید.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to علامت.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از اینکه پست الکترونیکی خود را تایید کردید متشکریم. لطفا از این لینک برای ورود به سیستم استفاده نمایید..
        /// </summary>
        public static string ThankYouForConfirmingYourEmailPleaseClickToLogin {
            get {
                return ResourceManager.GetString("ThankYouForConfirmingYourEmailPleaseClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید حداقل {2} کاراکتر باشد.
        /// </summary>
        public static string The0MusBeAtLeast2CharactersLong {
            get {
                return ResourceManager.GetString("The0MusBeAtLeast2CharactersLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور و تکرار رمز عبور با هم مطابقت ندارد.
        /// </summary>
        public static string ThePasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("ThePasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج شنبه.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تیر.
        /// </summary>
        public static string Tir {
            get {
                return ResourceManager.GetString("Tir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار کل قبول شده.
        /// </summary>
        public static string TotalAcceptedQty {
            get {
                return ResourceManager.GetString("TotalAcceptedQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار کل.
        /// </summary>
        public static string TotalQty {
            get {
                return ResourceManager.GetString("TotalQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمع کل.
        /// </summary>
        public static string TotalSum {
            get {
                return ResourceManager.GetString("TotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تراکنش.
        /// </summary>
        public static string TransDate {
            get {
                return ResourceManager.GetString("TransDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شرکت حمل و نقل.
        /// </summary>
        public static string TransportCompany {
            get {
                return ResourceManager.GetString("TransportCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلاش مجدد بوسیله جست جو.
        /// </summary>
        public static string TryWithASearch {
            get {
                return ResourceManager.GetString("TryWithASearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه شنبه.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایپ کنید و جست جو نمایید.
        /// </summary>
        public static string TypeAndSearch {
            get {
                return ResourceManager.GetString("TypeAndSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گارانتی.
        /// </summary>
        public static string UnderWarantyOf {
            get {
                return ResourceManager.GetString("UnderWarantyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین تبدیل واحد.
        /// </summary>
        public static string UnitConvertor {
            get {
                return ResourceManager.GetString("UnitConvertor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازگیری.
        /// </summary>
        public static string UnitOfMeasure {
            get {
                return ResourceManager.GetString("UnitOfMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه واحد اندازگیری.
        /// </summary>
        public static string UnitOfMeasureCategory {
            get {
                return ResourceManager.GetString("UnitOfMeasureCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در ورود به سیستم.
        /// </summary>
        public static string UnsuccessfulLoginWithService {
            get {
                return ResourceManager.GetString("UnsuccessfulLoginWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ورود حساب محلی خود را وارد نمایید.
        /// </summary>
        public static string UseALocalAccountToLogin {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور معتبر نمی باشد.
        /// </summary>
        public static string UsernameOrPasswordWasNotValid {
            get {
                return ResourceManager.GetString("UsernameOrPasswordWasNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار انتخاب شده باید بیشتر از صفر باشد.
        /// </summary>
        public static string ValueMustBeBiggerThanZero {
            get {
                return ResourceManager.GetString("ValueMustBeBiggerThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد باید بین 0 تا 10 باشد.
        /// </summary>
        public static string ValueOfThisFieldMustBetween0To10 {
            get {
                return ResourceManager.GetString("ValueOfThisFieldMustBetween0To10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات خودرو.
        /// </summary>
        public static string VehicleInfo {
            get {
                return ResourceManager.GetString("VehicleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع وسیله حمل و نقل.
        /// </summary>
        public static string VehicleType {
            get {
                return ResourceManager.GetString("VehicleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد بازدید.
        /// </summary>
        public static string VisitCount {
            get {
                return ResourceManager.GetString("VisitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدت زمان گارانتی.
        /// </summary>
        public static string WarantyTime {
            get {
                return ResourceManager.GetString("WarantyTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انبار.
        /// </summary>
        public static string Warehouse {
            get {
                return ResourceManager.GetString("Warehouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رسید انبار.
        /// </summary>
        public static string WarehouseReceipt {
            get {
                return ResourceManager.GetString("WarehouseReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخطار.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به نرم افزار انبارداری {0} خوش آمدید.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلی.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بلی پاک شود.
        /// </summary>
        public static string YesDeleteIt {
            get {
                return ResourceManager.GetString("YesDeleteIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رکورد با موفقیت خذف شد.
        /// </summary>
        public static string YourFileHasBeenDeleted {
            get {
                return ResourceManager.GetString("YourFileHasBeenDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات متوقف شد :).
        /// </summary>
        public static string YourFileIsSafe {
            get {
                return ResourceManager.GetString("YourFileIsSafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسورد شما مقداردهی دوباره شد.
        /// </summary>
        public static string YourPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعد انجام عملیات قادر به بازیابی نخواهید بود!.
        /// </summary>
        public static string YouWillNotBeAbleToRecoverThisRecord {
            get {
                return ResourceManager.GetString("YouWillNotBeAbleToRecoverThisRecord", resourceCulture);
            }
        }
    }
}
